### ISSUE TITLE
Reduce cppp_2019.jpg to below 100KB in size

### ISSUE THREAD

**Issue by claremacrae** [include-cpp/include-cpp.github.io#17]
cppp_2019.jpg gives an accessibility warning that it's over 100KB - so reduce its size, whilst trying to keep the quality up.

**Comment by brianlheim** [comment]
Using the export to jpeg feature in my image editor I arrived at this version, which is compressed to around 96KB at the same resolution. It's a bit grainier, but I can still make out everyone's faces alright. What do you think? I also tried only reducing the resolution, but to me the blurring was even worse than the compression artifacts. Maybe an alternative would be some combination of cropping and compression?

![cppp_2019](https://user-images.githubusercontent.com/15369640/106687740-0619fe80-65cd-11eb-8d47-ef161f1b1005.jpg)

**Comment by claremacrae** [comment]
This is great - thanks Brian... I see that the original was a bit grainy too - and the page width is limited by the design, so I think this is fine...

I'll go ahead and use it...
