### ISSUE TITLE
Create automated check for broken links on the site

### ISSUE THREAD

**Issue by claremacrae** [include-cpp/include-cpp.github.io#28]
Some of the links in Resources are probably broken, as the files were created a few years ago.

There are various [github actions for checking Markdown links](https://www.google.co.uk/search?q=github+action+check+markdown+links&oq=github+action+check+markdown+links)

It would be great to have one of those enabled on this site:

* ideally to check links on every push
* and also to run as a cron job, perhaps checking for broken links once a week?

**Comment by claremacrae** [comment]
I implemented something like this for ApprovalTests.cpp, so have cribbed the files, updated them for #include, and run them on the current content....

The output consists of:
* FILE: [markdown file name]
* any problem URLs...

The output is currently:

FILE: ./discord/index.md
FILE: ./code-of-conduct.md
[✖] http://citizencodeofconduct.org/
[✖] http://citizencodeofconduct.org/ → Status: 0
FILE: ./shop.md
FILE: ./resources/conference-resources.md
[✖] http://girlsintechuk.com/2014/11/12/where-are-all-the-women/
[✖] http://web.pipelineconf.info/about/code-of-conduct/
[✖] http://leanagile.scot/code-of-conduct/
[✖] http://girlsintechuk.com/2014/11/12/where-are-all-the-women/ → Status: 404
[✖] http://web.pipelineconf.info/about/code-of-conduct/ → Status: 0
[✖] http://leanagile.scot/code-of-conduct/ → Status: 404
FILE: ./resources/other_organisations.md
[✖] https://www.c4q.nyc/
[✖] https://www.momscancode.com/
[✖] https://www.c4q.nyc/ → Status: 0
[✖] https://www.momscancode.com/ → Status: 404
FILE: ./resources/index.md
FILE: ./resources/recruitment.md
[✖] http://blog.fogcreek.com/how-to-find-hire-and-retain-developers-interview-with-cal-evans/
[✖] http://blog.fogcreek.com/how-to-find-hire-and-retain-developers-interview-with-cal-evans/ → Status: 404
FILE: ./resources/equality_and_diversity.md
[✖] https://t.co/kdhUgzqLTM&quot;
[✖] http://www.shirky.com/weblog/2010/01/a-rant-about-women/
[✖] https://storify.com/EricaJoy/realdiversitynumbers
[✖] http://stackexchange.com/diversity&quot;
[✖] http://beero.ps/2015/03/03/on-breaking-out-of-echo-chambers/
[✖] http://narrowthegapp.com/
[✖] http://t.co/qCJCVzH1W8&quot;
[✖] https://t.co/kdhUgzqLTM&quot; → Status: 404
[✖] http://www.shirky.com/weblog/2010/01/a-rant-about-women/ → Status: 404
[✖] https://storify.com/EricaJoy/realdiversitynumbers → Status: 403
[✖] http://stackexchange.com/diversity&quot; → Status: 404
[✖] http://beero.ps/2015/03/03/on-breaking-out-of-echo-chambers/ → Status: 0
[✖] http://narrowthegapp.com/ → Status: 0
[✖] http://t.co/qCJCVzH1W8&quot; → Status: 404
FILE: ./README.md
FILE: ./template-page.md
FILE: ./index.md
FILE: ./what-can-i-do.md
FILE: ./conferences/scholarships.md
[✖] https://conference.accu.org/news/2020/202003121205_accu2020cancelled.html
[✖] https://conference.accu.org/news/2020/202003121205_accu2020cancelled.html → Status: 404
FILE: ./conferences/attending-conferences.md
FILE: ./conferences/organising-conferences.md
FILE: ./conferences/index.md
FILE: ./conferences/current_funding_campaign.md
FILE: ./moderation.md
[✖] https://github.com/gobridge/CodeOfConduct
[✖] https://github.com/gobridge/CodeOfConduct → Status: 404
At least one error found!

**Comment by claremacrae** [comment]
I've just re-run the link-checker, and all links now work....

```
./scripts/check_links.sh 
FILE: ./discord/index.md
FILE: ./code-of-conduct.md
FILE: ./shop.md
FILE: ./resources/conference-resources.md
FILE: ./resources/other_organisations.md
FILE: ./resources/index.md
FILE: ./resources/recruitment.md
FILE: ./resources/equality_and_diversity.md
FILE: ./README.md
FILE: ./template-page.md
FILE: ./index.md
FILE: ./what-can-i-do.md
FILE: ./conferences/scholarships.md
FILE: ./conferences/attending-conferences.md
FILE: ./conferences/organising-conferences.md
FILE: ./conferences/index.md
FILE: ./conferences/current_funding_campaign.md
FILE: ./moderation.md
```

I'll leave the ticket open until I've set up some way of triggering (manually or automatically) the checks via GitHub...

**Comment by bergjohan** [comment]
Should we close this now, or is there any reason to leave it open?

**Comment by claremacrae** [comment]
Good point - thanks!
